//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.ECShopService", ConfigurationName="IECShop")]
public interface IECShop
{
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetBrandTreeJson", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetBrandTreeJsonResponse")]
    string GetBrandTreeJson();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetBrandListByParentId", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetBrandListByParentIdResponse")]
    string GetBrandListByParentId(System.Guid parentId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetBrandListByCategoryId", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetBrandListByCategoryIdResponse")]
    string GetBrandListByCategoryId(System.Guid categoryId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetCategoryModel", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetCategoryModelResponse")]
    string GetCategoryModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetCategoryTreeJson", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetCategoryTreeJsonResponse")]
    string GetCategoryTreeJson();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetProductListByPage", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetProductListByPageResponse")]
    string GetProductListByPage(out int totalRecords, int pageIndex, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetProductListByCategory", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetProductListByCategoryResponse")]
    string GetProductListByCategory(out int totalRecords, int pageIndex, int pageSize, System.Guid categoryId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetProductListByBrand", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetProductListByBrandResponse")]
    string GetProductListByBrand(out int totalRecords, int pageIndex, int pageSize, System.Guid brandId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetProductListByMenu", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetProductListByMenuResponse")]
    string GetProductListByMenu(out int totalRecords, int pageIndex, int pageSize, System.Guid menuId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.ECShopService/IECShop/GetProductDetail", ReplyAction="TygaSoft.Services.ECShopService/IECShop/GetProductDetailResponse")]
    string GetProductDetail(System.Guid productId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IECShopChannel : IECShop, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ECShopClient : System.ServiceModel.ClientBase<IECShop>, IECShop
{
    
    public ECShopClient()
    {
    }
    
    public ECShopClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ECShopClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ECShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ECShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetBrandTreeJson()
    {
        return base.Channel.GetBrandTreeJson();
    }
    
    public string GetBrandListByParentId(System.Guid parentId)
    {
        return base.Channel.GetBrandListByParentId(parentId);
    }
    
    public string GetBrandListByCategoryId(System.Guid categoryId)
    {
        return base.Channel.GetBrandListByCategoryId(categoryId);
    }
    
    public string GetCategoryModel(System.Guid Id)
    {
        return base.Channel.GetCategoryModel(Id);
    }
    
    public string GetCategoryTreeJson()
    {
        return base.Channel.GetCategoryTreeJson();
    }
    
    public string GetProductListByPage(out int totalRecords, int pageIndex, int pageSize)
    {
        return base.Channel.GetProductListByPage(out totalRecords, pageIndex, pageSize);
    }
    
    public string GetProductListByCategory(out int totalRecords, int pageIndex, int pageSize, System.Guid categoryId)
    {
        return base.Channel.GetProductListByCategory(out totalRecords, pageIndex, pageSize, categoryId);
    }
    
    public string GetProductListByBrand(out int totalRecords, int pageIndex, int pageSize, System.Guid brandId)
    {
        return base.Channel.GetProductListByBrand(out totalRecords, pageIndex, pageSize, brandId);
    }
    
    public string GetProductListByMenu(out int totalRecords, int pageIndex, int pageSize, System.Guid menuId)
    {
        return base.Channel.GetProductListByMenu(out totalRecords, pageIndex, pageSize, menuId);
    }
    
    public string GetProductDetail(System.Guid productId)
    {
        return base.Channel.GetProductDetail(productId);
    }
}
