//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.HnztcService", ConfigurationName="IHnztc")]
public interface IHnztc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetSiteFunList", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetSiteFunListResponse")]
    string GetSiteFunList();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetAdvertisementList", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetAdvertisementListResponse")]
    string GetAdvertisementList(int pageIndex, int pageSize, System.Guid siteFunId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetAdvertisementModel", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetAdvertisementModelResponse")]
    string GetAdvertisementModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetAnnouncementList", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetAnnouncementListResponse")]
    string GetAnnouncementList(int pageIndex, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetAnnouncementModel", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetAnnouncementModelResponse")]
    string GetAnnouncementModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetNoticeListByPage", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetNoticeListByPageResponse")]
    string GetNoticeListByPage(out int totalRecords, int pageIndex, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetNoticeModel", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetNoticeModelResponse")]
    string GetNoticeModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetShopMenuListByRoot", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetShopMenuListByRootResponse")]
    string GetShopMenuListByRoot();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetContentTypeChildListByParentId", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetContentTypeChildListByParentIdResponse")]
    string GetContentTypeChildListByParentId(System.Guid parentId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetProvinceCityModel", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetProvinceCityModelResponse")]
    string GetProvinceCityModel(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetProvince", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetProvinceResponse")]
    string GetProvince();
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetCity", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetCityResponse")]
    string GetCity(System.Guid provinceId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetDistrict", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetDistrictResponse")]
    string GetDistrict(System.Guid cityId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetServiceList", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetServiceListResponse")]
    string GetServiceList(string username, int pageIndex, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetServiceListByServiceItemId", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetServiceListByServiceItemIdResponse")]
    string GetServiceListByServiceItemId(string username, int pageIndex, int pageSize, System.Guid serviceItemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetServiceVoteById", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetServiceVoteByIdResponse")]
    string GetServiceVoteById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetServiceContentById", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetServiceContentByIdResponse")]
    string GetServiceContentById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetServiceLinkById", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetServiceLinkByIdResponse")]
    string GetServiceLinkById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/SaveServiceUserVole", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/SaveServiceUserVoleResponse")]
    string SaveServiceUserVole(string username, System.Guid serviceItemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/SaveServiceUserPraise", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/SaveServiceUserPraiseResponse")]
    string SaveServiceUserPraise(string username, System.Guid serviceItemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/SaveUserSignIn", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/SaveUserSignInResponse")]
    string SaveUserSignIn(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetUserSignInByMonth", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetUserSignInByMonthResponse")]
    string GetUserSignInByMonth(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/SaveUserLevelByEnumSource", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/SaveUserLevelByEnumSourceResponse")]
    string SaveUserLevelByEnumSource(string username, string funName);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetUserLevelByEnumSource", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetUserLevelByEnumSourceResponse")]
    string GetUserLevelByEnumSource(string username, string funName);
    
    [System.ServiceModel.OperationContractAttribute(Action="TygaSoft.Services.HnztcService/IHnztc/GetAboutUs", ReplyAction="TygaSoft.Services.HnztcService/IHnztc/GetAboutUsResponse")]
    string GetAboutUs();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IHnztcChannel : IHnztc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HnztcClient : System.ServiceModel.ClientBase<IHnztc>, IHnztc
{
    
    public HnztcClient()
    {
    }
    
    public HnztcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HnztcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HnztcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HnztcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetSiteFunList()
    {
        return base.Channel.GetSiteFunList();
    }
    
    public string GetAdvertisementList(int pageIndex, int pageSize, System.Guid siteFunId)
    {
        return base.Channel.GetAdvertisementList(pageIndex, pageSize, siteFunId);
    }
    
    public string GetAdvertisementModel(System.Guid Id)
    {
        return base.Channel.GetAdvertisementModel(Id);
    }
    
    public string GetAnnouncementList(int pageIndex, int pageSize)
    {
        return base.Channel.GetAnnouncementList(pageIndex, pageSize);
    }
    
    public string GetAnnouncementModel(System.Guid Id)
    {
        return base.Channel.GetAnnouncementModel(Id);
    }
    
    public string GetNoticeListByPage(out int totalRecords, int pageIndex, int pageSize)
    {
        return base.Channel.GetNoticeListByPage(out totalRecords, pageIndex, pageSize);
    }
    
    public string GetNoticeModel(System.Guid Id)
    {
        return base.Channel.GetNoticeModel(Id);
    }
    
    public string GetShopMenuListByRoot()
    {
        return base.Channel.GetShopMenuListByRoot();
    }
    
    public string GetContentTypeChildListByParentId(System.Guid parentId)
    {
        return base.Channel.GetContentTypeChildListByParentId(parentId);
    }
    
    public string GetProvinceCityModel(System.Guid Id)
    {
        return base.Channel.GetProvinceCityModel(Id);
    }
    
    public string GetProvince()
    {
        return base.Channel.GetProvince();
    }
    
    public string GetCity(System.Guid provinceId)
    {
        return base.Channel.GetCity(provinceId);
    }
    
    public string GetDistrict(System.Guid cityId)
    {
        return base.Channel.GetDistrict(cityId);
    }
    
    public string GetServiceList(string username, int pageIndex, int pageSize)
    {
        return base.Channel.GetServiceList(username, pageIndex, pageSize);
    }
    
    public string GetServiceListByServiceItemId(string username, int pageIndex, int pageSize, System.Guid serviceItemId)
    {
        return base.Channel.GetServiceListByServiceItemId(username, pageIndex, pageSize, serviceItemId);
    }
    
    public string GetServiceVoteById(System.Guid Id)
    {
        return base.Channel.GetServiceVoteById(Id);
    }
    
    public string GetServiceContentById(System.Guid Id)
    {
        return base.Channel.GetServiceContentById(Id);
    }
    
    public string GetServiceLinkById(System.Guid Id)
    {
        return base.Channel.GetServiceLinkById(Id);
    }
    
    public string SaveServiceUserVole(string username, System.Guid serviceItemId)
    {
        return base.Channel.SaveServiceUserVole(username, serviceItemId);
    }
    
    public string SaveServiceUserPraise(string username, System.Guid serviceItemId)
    {
        return base.Channel.SaveServiceUserPraise(username, serviceItemId);
    }
    
    public string SaveUserSignIn(string username)
    {
        return base.Channel.SaveUserSignIn(username);
    }
    
    public string GetUserSignInByMonth(string username)
    {
        return base.Channel.GetUserSignInByMonth(username);
    }
    
    public string SaveUserLevelByEnumSource(string username, string funName)
    {
        return base.Channel.SaveUserLevelByEnumSource(username, funName);
    }
    
    public string GetUserLevelByEnumSource(string username, string funName)
    {
        return base.Channel.GetUserLevelByEnumSource(username, funName);
    }
    
    public string GetAboutUs()
    {
        return base.Channel.GetAboutUs();
    }
}
