//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("TygaSoft.Services.HnztcQueueService", ClrNamespace="TygaSoft.Services.HnztcQueueService")]

namespace TygaSoft.Services.HnztcQueueService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLevelInfo", Namespace="TygaSoft.Services.HnztcQueueService")]
    public partial class UserLevelInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EnumSourceField;
        
        private int FunCodeField;
        
        private bool IsReduceField;
        
        private int TotalGoldField;
        
        private int TotalIntegralField;
        
        private int TotalSilverField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnumSource
        {
            get
            {
                return this.EnumSourceField;
            }
            set
            {
                this.EnumSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunCode
        {
            get
            {
                return this.FunCodeField;
            }
            set
            {
                this.FunCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReduce
        {
            get
            {
                return this.IsReduceField;
            }
            set
            {
                this.IsReduceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalGold
        {
            get
            {
                return this.TotalGoldField;
            }
            set
            {
                this.TotalGoldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalIntegral
        {
            get
            {
                return this.TotalIntegralField;
            }
            set
            {
                this.TotalIntegralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalSilver
        {
            get
            {
                return this.TotalSilverField;
            }
            set
            {
                this.TotalSilverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessStatisticInfo", Namespace="TygaSoft.Services.HnztcQueueService")]
    public partial class AccessStatisticInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private bool IsReduceField;
        
        private string TableNameField;
        
        private System.Guid UserIdField;
        
        private int ViewCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReduce
        {
            get
            {
                return this.IsReduceField;
            }
            set
            {
                this.IsReduceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName
        {
            get
            {
                return this.TableNameField;
            }
            set
            {
                this.TableNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewCount
        {
            get
            {
                return this.ViewCountField;
            }
            set
            {
                this.ViewCountField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.HnztcQueueService", ConfigurationName="IUserBaseQueue")]
public interface IUserBaseQueue
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="TygaSoft.Services.HnztcQueueService/IUserBaseQueue/SaveUserLevel")]
    void SaveUserLevel(TygaSoft.Services.HnztcQueueService.UserLevelInfo userLevelInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IUserBaseQueueChannel : IUserBaseQueue, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class UserBaseQueueClient : System.ServiceModel.ClientBase<IUserBaseQueue>, IUserBaseQueue
{
    
    public UserBaseQueueClient()
    {
    }
    
    public UserBaseQueueClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserBaseQueueClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserBaseQueueClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserBaseQueueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveUserLevel(TygaSoft.Services.HnztcQueueService.UserLevelInfo userLevelInfo)
    {
        base.Channel.SaveUserLevel(userLevelInfo);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TygaSoft.Services.HnztcQueueService", ConfigurationName="IAccessStatisticQueue")]
public interface IAccessStatisticQueue
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="TygaSoft.Services.HnztcQueueService/IAccessStatisticQueue/SaveAccessStatistic")]
    void SaveAccessStatistic(TygaSoft.Services.HnztcQueueService.AccessStatisticInfo accessStatisticInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAccessStatisticQueueChannel : IAccessStatisticQueue, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AccessStatisticQueueClient : System.ServiceModel.ClientBase<IAccessStatisticQueue>, IAccessStatisticQueue
{
    
    public AccessStatisticQueueClient()
    {
    }
    
    public AccessStatisticQueueClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AccessStatisticQueueClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccessStatisticQueueClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccessStatisticQueueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveAccessStatistic(TygaSoft.Services.HnztcQueueService.AccessStatisticInfo accessStatisticInfo)
    {
        base.Channel.SaveAccessStatistic(accessStatisticInfo);
    }
}
